=== chingchangtw/gsa-valve-security-framework/gsaValveConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
        <xs:element name="GSAValveConfiguration">
            <xs:complexType>
     		<xs:sequence>
        		<xs:element name="loginUrl" type="xs:anyURI"/>
  				<xs:element name="authCookieDomain" type="xs:string" maxOccurs="1" minOccurs="1"/>
  				<xs:element name="authenticationProcessImpl" type="xs:string" maxOccurs="1" minOccurs="1"/>
  				<xs:element name="authenticateServletPath" type="xs:string" maxOccurs="1" minOccurs="1"/>
  				<xs:element name="authorizationProcessImpl" type="xs:string" maxOccurs="1" minOccurs="1"/>
  				<xs:element name="authCookiePath" type="xs:string" maxOccurs="1" minOccurs="1"/>
  				<xs:element name="authMaxAge" type="xs:integer" maxOccurs="1" minOccurs="1"/>
  				<xs:element name="searchHost" maxOccurs="unbounded" minOccurs="1" type="xs:string"/>
                                <xs:element name="maxConnectionsPerHost" type="xs:integer" maxOccurs="1" minOccurs="1"/>
                                <xs:element name="maxTotalConnections" type="xs:integer" maxOccurs="1" minOccurs="1"/>
                                <xs:element name="testFormsCrawlUrl" type="xs:string" maxOccurs="1" minOccurs="0"/>
                                <xs:element name="kerberos" ref="kerberos" maxOccurs="1" minOccurs="1"/>
                                <xs:element name="sessions" ref="sessions" maxOccurs="1" minOccurs="1"/>
                                <xs:sequence>
                                    <xs:element ref="repository" maxOccurs="unbounded"/>
                                </xs:sequence>
                </xs:sequence>
            </xs:complexType>
	</xs:element>

	
        <xs:element name="repository">
            <xs:complexType>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" ref="P"/>
                </xs:sequence>
                <xs:attribute name="authN" use="required" type="xs:string"/>
                <xs:attribute name="authZ" use="required" type="xs:string"/>
                <xs:attribute name="id" use="required" type="xs:string"/>
                <xs:attribute name="failureAllow" use="required" type="xs:string"/>
                <xs:attribute name="pattern" use="required" type="xs:anyURI"/>
            </xs:complexType>
        </xs:element>
  
        <xs:element name="P">
            <xs:complexType>
                <xs:attribute name="N" use="required" type="xs:string"/>
                <xs:attribute name="V" use="required" type="xs:string"/>
            </xs:complexType>
        </xs:element>
        
        <xs:element name="kerberos">
            <xs:complexType>
                <xs:attribute name="isKerberos" use="required" type="xs:string"/>
                <xs:attribute name="isNegotiate" use="optional" type="xs:string"/>
                <xs:attribute name="krbini" use="optional" type="xs:string"/>
                <xs:attribute name="krbconfig" use="optional" type="xs:string"/>
                <xs:attribute name="krbAdditionalAuthN" use="optional" type="xs:string"/>
                <xs:attribute name="krbLoginUrl" use="optional" type="xs:string"/>
                <xs:attribute name="krbUsrPwdCrawler" use="optional" type="xs:string"/>
                <xs:attribute name="krbUsrPwdCrawlerUrl" use="optional" type="xs:string"/>
            </xs:complexType>
        </xs:element>
        
        <xs:element name="sessions">
            <xs:complexType>
                <xs:attribute name="isSessionEnabled" use="required" type="xs:string"/>
                <xs:attribute name="sessionTimeout" use="optional" type="xs:string"/>
                <xs:attribute name="maxSessionAge" use="optional" type="xs:string"/>
                <xs:attribute name="sessionCleanup" use="optional" type="xs:string"/>
                <xs:attribute name="sendCookies" use="optional" type="xs:string"/>
            </xs:complexType>
        </xs:element>
</xs:schema>

=== chingchangtw/gsa-valve-security-framework/trunk/gsaValveConfig.xml
<?xml version="1.0"?>
<GSAValveConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///I:/My Documents/code and feeds/ValveDevelopment/gsaValveConfiguration.xsd">

<!-- General Valve Configuration  -->
<loginUrl>http://valve.google.com:8080/valve/login.jsp</loginUrl>
<authCookieDomain>.google.com</authCookieDomain>
<authenticationProcessImpl>com.google.gsa.valve.rootAuth.RootAuthenticationProcess</authenticationProcessImpl>
<authenticateServletPath>/Authenticate</authenticateServletPath>
<authorizationProcessImpl>com.google.gsa.valve.rootAuth.RootAuthorizationProcess</authorizationProcessImpl>
<authCookiePath>/</authCookiePath>
<authMaxAge>-1</authMaxAge>
<authCookieName>gsaSSOCookie</authCookieName>
<searchHost>http://gsa1.google.com</searchHost>
<searchHost>http://gsa2.google.com</searchHost>
<maxConnectionsPerHost>10</maxConnectionsPerHost>
<maxTotalConnections>300</maxTotalConnections>
<testFormsCrawlUrl>http://clazaroT60-es.corp.google.com:8080/valve/test.html</testFormsCrawlUrl>

<!-- Kerberos config. If you're not using at all just configure the first two attributes -->
<kerberos isKerberos="false"
          isNegotiate="false"
	  krbini="c:\\Program Files\\Tomcat5.5kerb\\conf\\spnego\\krb5.ini"
	  krbconfig="c:\\Program Files\\Tomcat5.5kerb\\conf\\spnego\\bcsLogin.conf"
	  krbAdditionalAuthN="false"
	  krbLoginUrl="http://valve.google.com:5080/valve/loginkrb.jsp"
	  krbUsrPwdCrawler="false"
	  krbUsrPwdCrawlerUrl="http://valve.google.com:5080/valve/logincrawlerkrb.jsp"/>

<!-- Session config. If you're not using at all just configure the first attribute -->
<sessions isSessionEnabled="false"
	  sessionTimeout="30"
	  maxSessionAge="360"
	  sessionCleanup="15"
	  sendCookies="true"/>


<!-- THE NEXT REPOSITORIES ARE JUST EXAMPLES. USE YOUR OWN REPOSITORIES CONFIGURATION -->

<!-- This is an Active Directory integration sample -->
<repository id="root" pattern="valve.google.com" authN="com.google.gsa.valve.modules.ldap.LDAPUniqueCreds" authZ="" failureAllow="true">
	
	<P N="ldapBaseuser" V="dc=enterprise,dc=google,dc=com"/>
	<P N="ldapHost" V="ldap://ad.google.com:389"/>
	<P N="ldapDomain" V="@enterprise.google.com"/>
	<P N="rdnAttr" V="cn"/>
</repository>


<!-- This is an HTTP Basic sample -->
<repository id="HTTPBasicAuth" pattern="http://server.google.com:90" 
	authN="com.google.gsa.valve.modules.httpbasic.HTTPBasicAuthenticationProcess" authZ="com.google.gsa.valve.modules.httpbasic.HTTPBasicAuthorizationProcess" failureAllow="true">
	<P N="HTTPAuthPage" V="http://server.google.com:90/"/>
</repository>

</GSAValveConfiguration>

=== chingchangtw/gsa-valve-security-framework/gsaValveConfig.xml
<?xml version="1.0"?>
<GSAValveConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///I:/gsaValveConfiguration.xsd">

<!-- General Valve Configuration  -->
<!-- change the following sample values with those for your environment (google.com here is just a sample corporate domain) -->
<loginUrl>http://valve.google.com:8080/valve/login.jsp</loginUrl>
<authCookieDomain>.google.com</authCookieDomain>
<authenticationProcessImpl>com.google.gsa.valve.rootAuth.RootAuthenticationProcess</authenticationProcessImpl>
<authenticateServletPath>/Authenticate</authenticateServletPath>
<authorizationProcessImpl>com.google.gsa.valve.rootAuth.RootAuthorizationProcess</authorizationProcessImpl>
<authCookiePath>/</authCookiePath>
<authMaxAge>-1</authMaxAge>
<authCookieName>gsaSSOCookie</authCookieName>
<refererCookieName>gsaReferer</refererCookieName>
<searchHost>http://gsa1.google.com</searchHost>
<!-- add here more search appliance if needed. For example -->
<!-- <searchHost>http://gsa2.google.com</searchHost> -->
<maxConnectionsPerHost>60</maxConnectionsPerHost>
<maxTotalConnections>300</maxTotalConnections>
<testFormsCrawlUrl>http://valve.google.com:8080/valve/test.html</testFormsCrawlUrl>
<errorLocation>C:\\Tomcat\\webapps\\valve\\WEB-INF\\error</errorLocation>

<!-- Kerberos config. If you're not using at all just set the first two attributes to false (the rest are discarded) -->
<kerberos isKerberos="false"
          isNegotiate="false"
	  krbini="c:\\Windows\\krb5.ini"
	  krbconfig="c:\\Tomcat\\conf\\spnego\\bcsLogin.conf"
	  krbAdditionalAuthN="false"
	  krbLoginUrl="http://valve.google.com:5080/valve/loginkrb.jsp"
	  krbUsrPwdCrawler="false"
	  krbUsrPwdCrawlerUrl="http://valve.google.com:5080/valve/logincrawlerkrb.jsp"/>

<!-- Session config. If you're not using at all just set the first attribute to false (the rest are discarded) -->
<sessions isSessionEnabled="false"
	  sessionTimeout="-1"
	  maxSessionAge="360"
	  sessionCleanup="15"
	  sendCookies="true"/>

<!-- Saml config -->
<saml     isSAML="false" 
          maxArtifactAge="60"
          samlTimeout="360"/>

<!-- THE NEXT REPOSITORIES ARE JUST EXAMPLES. USE YOUR OWN REPOSITORIES CONFIGURATION -->

<!-- This is an Active Directory integration sample -->
<repository id="root" pattern="valve.google.com" authN="com.google.gsa.valve.modules.ldap.LDAPUniqueCreds" authZ="" failureAllow="true" checkAuthN="true">
	
	<P N="ldapBaseuser" V="dc=enterprise,dc=google,dc=com"/>
	<P N="ldapHost" V="ldap://ad.google.com:389"/>
	<P N="ldapDomain" V="@enterprise.google.com"/>
	<P N="rdnAttr" V="cn"/>
</repository>


<!-- This is an HTTP Basic sample -->
<repository id="HTTPBasicAuth" pattern="http://server.google.com:90" 
	authN="com.google.gsa.valve.modules.httpbasic.HTTPBasicAuthenticationProcess" authZ="com.google.gsa.valve.modules.httpbasic.HTTPBasicAuthorizationProcess" failureAllow="true" checkAuthN="true">
	<P N="HTTPAuthPage" V="http://server.google.com:90/"/>
</repository>

</GSAValveConfiguration>
